# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('handle', models.CharField(max_length=20)),
                ('joined', models.DateField()),
                ('is_active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summery', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('is_draft', models.BooleanField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watsontutapp.Blogger')),
            ],
        ),
    ]
